{% set name = "ecp-cookie-init" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: ff9f957563910c13923ddb87989a7cd1409d4fb97520233ac7a322952d0e0620
  patches:
    - prefix.patch

build:
  number: 0
  script: install --mode=0755 "ecp-cookie-init" "${PREFIX}/bin/ecp-cookie-init"
  skip: true  # [win]

requirements:
  build:
    - coreutils
  run:
    - bash >=4
    - ca-certificates
    - curl >=7.19.7
    - krb5
    - libxslt >=1.1.26
    - openssl
    - python >=2.7

test:
  commands:
    - ecp-cookie-init -h
    - ecp-cookie-init -v

about:
  home: https://wiki.ligo.org/AuthProject
  dev_url: https://git.ligo.org/authpublic/ecp-cookie-init
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Utility for obtaining short-lived cookies for accessing Shibbolized SPs from command-line tools (e.g., curl or git)

extra:
  recipe-maintainers:
    - duncanmmacleod
