{% set name = "frv" %}
{% set version = "4.35.1" %}

{% set framel_version = "8.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: http://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.xz
  url: C:\Users\spxdmm\src\frv-4.35.1.tar.xz
  sha256: 98239696cebdb05d3be21ee64fe41af5ac05d8728cb9fb880e39e8103cc9284b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - pkg-config
  host:
    - fftw
    - libframel >={{ framel_version }}
  run:
    - fftw
    - libframel >={{ framel_version }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion --print-errors frv

about:
  home: https://git.ligo.org/virgo/virgoApp/Frv/
  dev_url: https://git.ligo.org/virgo/virgoApp/Frv/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The Frame Vector Library (Frv)

extra:
  recipe-maintainers:
    - duncanmmacleod
