{% set name = "gds-dmt" %}
{% set version = "2.19.7" %}

# dependencies
{% set gds_base_version = "2.19.8" %}
{% set gds_lsmp_version = "2.19.8" %}
{% set gds_frameio_version = "2.19.6" %}
{% set gds_gui_version = "2.19.7" %}
{% set ldas_tools_framecpp_version = "2.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 43a717cacb2151e3dc9e91ef1bffce777527550b793f33ac47bebaf5754422e0
  patches:
    # https://git.ligo.org/gds/gds/-/issues/100
    - rootlogon-macros-path.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - gds-base >={{ gds_base_version }}
    - gds-base-gdstrig >={{ gds_base_version }}
    - gds-base-monitors >={{ gds_base_version }}
    - gds-frameio-base >={{ gds_frameio_version }}
    - gds-gui-crtools >={{ gds_gui_version }}
    - gds-lsmp >={{ gds_lsmp_version }}
    - gds-services >={{ gds_base_version }}
    - jsoncpp
    - ldas-tools-al
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - root_base

outputs:
  - name: gds-dmt-base
    script: install-base.sh
    build:
      ignore_run_exports:
        # headers used, not linked
        - gds-services
      run_exports:
        - {{ pin_subpackage("gds-dmt-base", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
      host:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - gds-services >={{ gds_base_version }}
        - ldas-tools-al
      run:
        - gds-base >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - ldas-tools-al
        # over-linked on linux, https://git.ligo.org/gds/gds/-/merge_requests/187
        - gds-lsmp >={{ gds_lsmp_version }}  # [linux]
        - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}  # [linux]
    test:
      requires:
        - pkg-config
        # required by gdsdmtenv.pc, not linked
        - gds-base-gdstrig
        - gds-base-monitors
      commands:
        - test -f ${PREFIX}/lib/libcalcengn${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libdmtenv${SHLIB_EXT}
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtcalcengine
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtenv
    about:
      home: https://git.ligo.org/gds/gds/
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: Core DMT package Core libraries
      description: |
        Core libraries required by the rest of the GDS DMT packages

  - name: gds-dmt-monitors
    script: install-monitors.sh
    build:
      run_exports:
        - {{ pin_subpackage("gds-dmt-monitors", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
      host:
        - gds-base >={{ gds_base_version }}
        - gds-base-gdstrig >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - jsoncpp
        - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
        - root_base
      run:
        - gds-base >={{ gds_base_version }}
        - gds-base-gdstrig >={{ gds_base_version }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - jsoncpp
        - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
        - root_base
        # over-linked on linux, https://git.ligo.org/gds/gds/-/merge_requests/187
        - gds-lsmp >={{ gds_lsmp_version }}  # [linux]
        - ldas-tools-al  # [linux]
    test:
      requires:
        - pkg-config
      commands:
        - test -x ${PREFIX}/bin/DMTGen
        - test -f ${PREFIX}/lib/libezcalib${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libgenerator${SHLIB_EXT}
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtezcalib
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtosc
        - pkg-config --print-errors --exact-version "{{ version }}" gdsdmtplotpkg
    about:
      home: https://git.ligo.org/gds/gds/
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: Libraries used by DMT Monitor programs
      description: |
        Libraries used by GDS DMT Monitor programs

  - name: gds-dmt-root
    script: install-root.sh
    requirements:
      build:
        - make
      host:
        - root_base
      run:
        - {{ pin_subpackage("gds-dmt-monitors", exact=True) }}
        - gds-frameio-base >={{ gds_frameio_version }}
        - gds-root-extensions-base
        - gds-root-extensions-crtools
        - root_base
    test:
      commands:
        - cp ${PREFIX}/share/gds/.rootrc .
        - cp ${PREFIX}/share/gds/macros/rootlogon.C .
        - root -b -l -q -x
    about:
      home: https://git.ligo.org/gds/gds/
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: ROOT wrapper for GDS classes
      description: |
        Root interpreter wrappers of some of the most useful GDS classes

about:
  home: https://git.ligo.org/gds/gds/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: LIGO Global Diagnostics System DMT subsystem

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
